name: npr

dependencies:
  - python=3.9 # change python version
  - pip
  - pip:
    #- e . # install package from current directory
    - pre-commit
    - jupyterlab
    - nltk
    - matplotlib
    - seaborn
    - pandas
    - numpy
